// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seminary.Model;

#nullable disable

namespace Seminary.Model.Migrations
{
    [DbContext(typeof(SeminaryContext))]
    [Migration("20231115174243_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Seminary.Model.ClassStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeacherId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("amountStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("Seminary.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Seminary.Model.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Seminary.Model.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.Property<int?>("Subjectid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Subjectid")
                        .IsUnique()
                        .HasFilter("[Subjectid] IS NOT NULL");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Seminary.Model.ClassStudent", b =>
                {
                    b.HasOne("Seminary.Model.Teacher", "TeacherOfClass")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherOfClass");
                });

            modelBuilder.Entity("Seminary.Model.Student", b =>
                {
                    b.HasOne("Seminary.Model.ClassStudent", "MyClass")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.Navigation("MyClass");
                });

            modelBuilder.Entity("Seminary.Model.Subject", b =>
                {
                    b.HasOne("Seminary.Model.ClassStudent", "SubjectToClass")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.Navigation("SubjectToClass");
                });

            modelBuilder.Entity("Seminary.Model.Teacher", b =>
                {
                    b.HasOne("Seminary.Model.ClassStudent", "TeacherOfSubjec")
                        .WithOne()
                        .HasForeignKey("Seminary.Model.Teacher", "Subjectid");

                    b.Navigation("TeacherOfSubjec");
                });
#pragma warning restore 612, 618
        }
    }
}
